//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PractikaOleshki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public string ArticleNumber { get; set; }
        public int Name { get; set; }
        public string Description { get; set; }
        public int Unit { get; set; }
        public int Category { get; set; }
        public byte[] Photo { get; set; }
        public int Manufacturer { get; set; }
        public decimal Cost { get; set; }
        public Nullable<int> DiscountAmount { get; set; }
        public int QuantityInStock { get; set; }
        public int Providers { get; set; }
        public int CurrentDiscoount { get; set; }
    
        public virtual fk_order_category fk_order_category { get; set; }
        public virtual fk_order_manufacrure fk_order_manufacrure { get; set; }
        public virtual fk_order_maxDiscount fk_order_maxDiscount { get; set; }
        public virtual fk_order_name fk_order_name { get; set; }
        public virtual fk_order_provaides fk_order_provaides { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual SI SI { get; set; }
    }
}
